version: "3"

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - static:/static
            - /etc/letsencrypt/archive/pitmarket.org:/etc/nginx/ssl/pitmarket.org
            - /root/pitmarket/uploads:/code/pitmarket_root/media/uploads
        depends_on:
            - django_gunicorn
    django_gunicorn:
        volumes:
            - static:/static
            - /root/pitmarket/db/db.sqlite3:/code/pitmarket_root/db.sqlite3
            - /root/pitmarket/uploads:/code/pitmarket_root/media/uploads
        build:
            context: .
        ports:
            - "8000:8000"
        depends_on:
            - redis
    redis:
        image: redis
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
    certbot:
        image: certbot/certbot
volumes:
    static:
