# Generated by Django 4.0.4 on 2022-06-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_bodytext_page_content_remove_page_update_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
