# Generated by Django 4.0.4 on 2022-06-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='publish_date',
            new_name='upload_date',
        ),
    ]
