# Generated by Django 4.1 on 2022-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_blogpost_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='upload_date',
            field=models.DateField(auto_now_add=True, verbose_name='Publish Date'),
        ),
    ]
