# Generated by Django 4.1 on 2022-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('item', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('list_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
