# Generated by Django 4.1 on 2022-08-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(auto_now_add=True, verbose_name='List Date'),
        ),
    ]
