# Generated by Django 4.1 on 2022-08-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='idk', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
