# Generated by Django 4.1 on 2022-08-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_id',
            new_name='id',
        ),
    ]
