# Generated by Django 4.1 on 2022-09-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='username',
        ),
    ]
